### ISSUE TITLE
Have filenames include the email address in the filename to allow easy opening in excel.

### ISSUE THREAD

**Issue by Absoblogginlutely** [Canthv0/hawk#17]
The current methodology creates a file similar to 
yyyymmddhh_mm\emailaddress\\User_Changes.csv
Each user has their own file in their own directory but they are all called user_changes.csv
Attempting to double click to open in Excel gives an error that you can't open more than one file with the same name.

Suggestion would be to encode the upn in the filename as well as the  foldername.

Should this be a pull request with the changes made? Should it be a feature request?

**Comment by Canthv0** [comment]
Good suggestion.  I implemented it in 1.13 ... let me know if it is causing issues.
