### ISSUE TITLE
Update how Dates are handled

### ISSUE THREAD

**Issue by Canthv0** [Canthv0/hawk#24]
Currently Dates are handled as a string conversion into the Hawk Global Object.  This works great as long as you are using the US date format.  From non-us date formats this is causing issues.

Need to move this to holding an actual Date object instead of a string version.

All of the searches are going to need to move to proper processing of dates (some of them don't take date objects and require strings)

**Comment by chingf0rd** [comment]
Would it be possible to put a UTC or TZ indicator too please? Noticed some fields extracted are local time whilst some are UTC.

**Comment by Canthv0** [comment]
Now storing dates as [datetime] objects instead of strings
updated all cmdlets to support the new objects

@chingf0rd  that work is outside the scope of this issue.  I will open a new issue for that and request feedback.

Fixed in version 1.13.7
