### ISSUE TITLE
Errors for Start-HawkTenantInvestigation

### ISSUE THREAD

**Issue by T-Bairadai** [Canthv0/hawk#29]
[16/10/2019 9:15:04 PM] - Starting Tenant Sweep
Out-Log : The term 'Out-Log' is not recognized as the name of a cmdlet, function, script file, or operable program.

Out-Log "Running Get-HawkTenantConfiguration" -action"

**Should it be** 
Out-LogFile "Running Get-HawkTenantConfiguration" -action"

**Comment by Absoblogginlutely** [comment]
Yes it should - I checked the code and there is no out-log but I think I remember seeing that issue before - I would check that you are running the latest version.
It should be 1.14.0 which is displayed when you first run start-hawktenantinvestigation

**Comment by Absoblogginlutely** [comment]
The code in the github repository is correct and either uses out-logfile or doesn't write to the logfile at all.
The code in the downloaded repository does use these statements as follows.
Modules\HAWK\1.14.0\Tenant\Start-HawkTenantInvestigation.ps1 (4 hits)
	Line 7: 	Out-Log "Running Get-HawkTenantConfiguration" -action
	Line 10: 	Out-Log "Running Get-HawkTenantEDiscoveryConfiguration" -action
	Line 13: 	Out-Log "Running Get-HawkTenantEXOAuditLog" -action
	Line 16: 	Out-Log "Running Get-HawkTenantRBACChanges" -action

Replace these with the file from https://raw.githubusercontent.com/Canthv0/hawk/master/Tenant/Start-HawkTenantInvestigation.ps1 and you should be good.
@Canthv0 , I'm guessing the process of updating from github to the powershell repository has issues?

**Comment by Canthv0** [comment]
There was a mismatch between the github code and the powershellgallery code that was caused by me being stupid and updating github with the fix but not gallery.

This has been corrected and both are now showing the same values.
