### ISSUE TITLE
Module calls function from CloudConnect module

### ISSUE THREAD

**Issue by wiseleaf23** [Canthv0/hawk#3]
The module calls some functions from the CloudConnect module, which is not installed by default and will throw an error. I suggest just prompting the user to connect to EXO (just like the MSOL prompt at the start of the script).

Start-HawkUserInvestigation -UserPrincipalName user@domain.nl -Verbose

**Comment by Canthv0** [comment]
CloudConnect is listed as a requiredmodule in the manifest for Hawk.  So it should be loading.

If it is not installing please let me know and I will adjust the manifest to ensure that it does.
Requiring this module is part of the ongoing work within Hawk to allow it to support MFA protected accounts.

**Comment by wiseleaf23** [comment]
I tested this on a clean instance, and got the same error about the Connect-EXO cmdlet:

```
Connect-EXO : The term 'Connect-EXO' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\HAWK\1.10.1\Hawk.psm1:744 char:9
+         Connect-EXO
+         ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-EXO:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by Canthv0** [comment]
I just tested this on a clean machine as well.

PS C:\windows\system32> get-command Install-Module

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        Install-Module                                     1.0.0.1    PowerShellGet


PS C:\windows\system32> Install-Module hawk

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or
'C:\Users\matbyrd\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install
and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PS C:\windows\system32> Get-Module hawk -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.10.1     HAWK                                {Get-HawkTenantAzureAuthenticationLogs, Get-HawkTenantConf...


PS C:\windows\system32> Get-Module cloud* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.2      CloudConnect                        {Get-ServiceToken, Get-TokenCache, Connect-EXO, Connect-EX...

Everything worked as expected.
Are you using Install-Module?
Ensure that you have updated the PowerShellGet Module.

Unfortunately I am not able to get a repro of this issue. ... with out a repro there is nothing that I can do to move this forward.

**Comment by wiseleaf23** [comment]
I will try again in a few days with a new Windows 10 build and the most recent version of the PS module and see if the problem persists. If it persists I will let you know the detailed steps and errors.

Thanks :)

**Comment by wiseleaf23** [comment]
Also was not able to reproduce this a second time on a clean VM. Maybe a PowerShell reboot was needed or I just did something wrong. Thank you for the active issue-resolving!
