### ISSUE TITLE
Searching mailbox audit logs will return multiple errors

### ISSUE THREAD

**Issue by wiseleaf23** [Canthv0/hawk#6]
While searching the mailbox audit logs, multiple errors will be returned, which will eventually end up in what looks like a loop:
Start-HawkUserInvestigation -UserPrincipalName user@domain.nl -Verbose

[4-7-2019 09:00:12] - Searching Exchange Mailbox Audit Logs (this can take some time)
Get-Date : Cannot bind parameter 'Date'. Cannot convert value "05/27/2019" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
At C:\Program Files\WindowsPowerShell\Modules\HAWK\1.8.7\User\Get-HawkUserMailboxAuditing.ps1:66 char:53
+ ...         [string]$RangeEnd = get-date ((Get-date ($RangeStart)).AddDay ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.GetDateCommand

[4-7-2019 09:00:12] - Searching Range 05/27/2019 To
Get-Date : Cannot bind parameter 'Date' to the target. Exception setting "Date": "Cannot convert null to type "System.DateTime"."
At C:\Program Files\WindowsPowerShell\Modules\HAWK\1.8.7\User\Get-HawkUserMailboxAuditing.ps1:66 char:53
+ ...         [string]$RangeEnd = get-date ((Get-date ($RangeStart)).AddDay ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.GetDateCommand

[4-7-2019 09:00:44] - Searching Range  To
Get-Date : Cannot bind parameter 'Date' to the target. Exception setting "Date": "Cannot convert null to type "System.DateTime"."
At C:\Program Files\WindowsPowerShell\Modules\HAWK\1.8.7\User\Get-HawkUserMailboxAuditing.ps1:66 char:53
+ ...         [string]$RangeEnd = get-date ((Get-date ($RangeStart)).AddDay ...
+                                                     ~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-Date], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.GetDateCommand

**Comment by Canthv0** [comment]
I believe that this should be fixed in the latest version.  It appears to have been an issue with non US date formats.  Give it a try now and let me know

**Comment by wiseleaf23** [comment]
I can confirm that this is fixed :)
