### ISSUE TITLE
Would retrieving users sent emails be useful as part of this report.

### ISSUE THREAD

**Issue by Absoblogginlutely** [Canthv0/hawk#8]
After detecting a compromised account, in my experience it's useful to check the sent items for emails that the user has sent out to see how bad the scope of compromise is (assuming the attack spammed out everyone in the contact list).
Would adding a feature to the script that runs a message trace to a csv for the user for the past X days (based on the original tenant day score) or the past 2 days be useful or would this be considered bloat for the project?

**Comment by Canthv0** [comment]
Added in 1.11.0
